apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-renderer-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: spa-renderer
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: spa-renderer
        branch: {{ git_branch }}
    spec:
      containers:
        - name: spa-renderer-container
          image: ghcr.io/ruchira088/video-downloader-spa-renderer:{{ git_branch }}-{{ git_commit }}
          readinessProbe:
            httpGet:
              port: expressjs-port
              path: /service/information
              httpHeaders:
                - name: X-Request-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: expressjs-port
              path: /service/information
              httpHeaders:
                - name: X-Request-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              port: expressjs-port
              path: /service/information
              httpHeaders:
                - name: X-Request-ID
                  value: k8s-liveness-probe
          ports:
            - name: expressjs-port
              containerPort: 8000
      imagePullSecrets:
        - name: docker-registry-credentials