- name: Create output directory
  file:
    path: output/docker
    state: directory

- name: Gather git information
  import_tasks: git-info.yml

- name: Generate the Dockerfile
  template:
    src: docker/Dockerfile
    dest: output/docker/Dockerfile
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Build Docker image
  shell: |
    docker build \
      -f output/docker/Dockerfile \
      -t video-downloader-spa-renderer:{{ git_branch }} \
      -t video-downloader-spa-renderer:{{ git_branch }}-{{ git_commit }} \
      ../

- name: Cleanup output directory
  file:
    path: output/docker
    state: absent
