- name: Create output directory
  file:
    path: output/docker
    state: directory

- name: Gather git information
  import_tasks: git-info.yml

- name: Generate the Dockerfile
  template:
    src: docker/Dockerfile
    dest: output/docker/Dockerfile
  vars:
    build_timestamp: "{{ ansible_date_time.iso8601 }}"