---
- hosts: localhost
  connection: local

  tasks:
    - name: Render Dockerfile
      import_tasks: tasks/render-dockerfile.yml

    - name: Login to Docker Hub
      command: docker login -u {{ docker_username }} -p {{ docker_password }}
      vars:
        docker_username: "{{ lookup('aws_ssm', '/docker-hub/credentials/username', region='ap-southeast-2') }}"
        docker_password: "{{ lookup('aws_ssm', '/docker-hub/credentials/password', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ruchira088/video-downloader-spa-renderer:{{ git_branch }}-{{ git_commit }} \
          -f output/docker/Dockerfile \
          ../

    - name: Cleanup output directory
      file:
        path: output/docker
        state: absent
