name: Deploy Health Check SPA

on:
  push:
    branches:
      - dev

concurrency:
  group: health-check-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ./health-check-spa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: backend-deploy
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform
        working-directory: ./health-check-spa/terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./health-check-spa/terraform
        run: terraform apply -auto-approve

  send-notification:
    runs-on: ubuntu-latest
    if: always()

    permissions:
      id-token: write

    needs:
      - build-and-deploy

    steps:
      - name: Send Slack notification
        uses: ruchira088/slack-github-action@v1
